name: "Common Airport Checkin"

on:
  push:
    branches: [ master ]  # 在推送到 master 分支时触发
  schedule:
    - cron: "0 22 * * *"  # 每天 UTC 22:00 (即 UTC+8 06:00) 运行
  workflow_dispatch:  # 保留手动触发选项

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create config file
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          echo "$CONFIG" > config.json

      - name: Run sign
        run: |
          python3 ./main.py