name: "Common Airport Checkin"

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create and check config file
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          echo "$CONFIG" > config.json
          echo "Config file contents (first 10 lines):"
          head -n 10 config.json
          echo "---"
          echo "Is config.json valid JSON?"
          python -c "import json; json.load(open('config.json'))" && echo "Yes, it's valid JSON" || echo "No, it's not valid JSON"

      - name: Run sign
        run: |
          python3 ./main.py

      - name: Output run logs
        if: always()
        run: |
          echo "=== Script Output ==="
          cat output.log
        continue-on-error: true
