name: "Common Airport Checkin"

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sign
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          python3 ./main.py

      - name: Output run logs
        if: always()
        run: |
          echo "=== Script Output ==="
          cat output.log
        continue-on-error: true
